twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    globals:
        ingredients_directory: '%ingredients_directory%'
        cocktails_directory: '%cocktails_directory%'
        uploads_directory: '%uploads_directory%'
        app_version: '%env(APP_VERSION)%'
        appConfig: '@App\Service\ConfigService'
    paths:
        '%kernel.project_dir%/assets/styles': styles
when@test:
    twig:
        strict_variables: true
