twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        ingredients_directory: '%ingredients_directory%'
        cocktails_directory: '%cocktails_directory%'
when@test:
    twig:
        strict_variables: true
