twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/types.html.twig'
        - 'bootstrap_5_layout.html.twig'
    globals:
        ingredients_directory: '%ingredients_directory%'
        cocktails_directory: '%cocktails_directory%'
        app_version: '%env(APP_VERSION)%'
when@test:
    twig:
        strict_variables: true
